generate:
	kitex \
	-service "tiktok-comment" \
	-module "github.com/ozline/tiktok" \
	-type protobuf \
	-I ./../../idl/ comment.proto

# Service: comment
# Path: services/comment
# Optional: -use "github.com/ozline/tiktok/kitex_gen"