linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - typecheck
    - unused
    - misspell
    - nolintlint
    - goimports
    - nakedret
    - unconvert
    - whitespace
    - govet
    - gosimple
    - ineffassign
    - gocritic
linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - lostcancel
      - shadow