version: '3.7'

networks:
    tiktok:
        driver: bridge

services:

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tiktok
            - MYSQL_USER=tiktok
            - MYSQL_PASSWORD=tiktok
            - TZ=Asia/Shanghai
        volumes:
            - ./config/sql:/docker-entrypoint-initdb.d/
        ports:
            - "3306:3306"
        networks:
            - tiktok

    redis:
        container_name: redis
        image: "redis:latest"
        restart: always
        ports:
            - 6379:6379
        volumes:
            - /usr/local/redis/conf/redis.conf:/var/lib/redis/conf/redis.conf
            - /usr/local/redis/data:/data
        environment:
            - REDIS_PASSWORD=tiktok
            - ALLOW_EMPTY_PASSWORD=no
        networks:
                - tiktok

    rabbitmq:
        container_name: rabiitmq
        image: "rabbitmq:latest"
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=tiktok
            - RABBITMQ_DEFAULT_PASS=tiktok
        networks:
            - tiktok

    etcd:
        container_name: etcd
        image: "quay.io/coreos/etcd:v3.5.5"
        restart: always
        ports:
            - "2379:2379"
        environment:
            - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
            - ETCD_API=3
        networks:
            - tiktok

    jaeger:
        container_name: jaeger
        image: "jaegertracing/all-in-one:latest"
        restart: always
        ports:
            - 16686:16686
            - 6831:6831/udp
        networks:
            - tiktok

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        networks:
            - tiktok

    alertmanager:  #预警模块
        image: prom/alertmanager
        container_name: alertmanager
        restart: always
        ports:
            - 9093:9093
        networks:
            - tiktok

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - tiktok

    node-exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        restart: always
        ports:
            - 9100:9100
        networks:
            - tiktok

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        restart: always
        platform: linux/amd64
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - "8899:8080"
        networks:
            - tiktok

    redis-exporter:
        image: oliver006/redis_exporter
        container_name: redis-exporter
        restart: always
        ports:
            - 9121:9121
        command:
            - "--redis.addr=redis://127.0.0.1:6379"
        networks:
            - tiktok

    mysql_xporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        restart: always
        ports:
            - 9104:9104
        environment:
            DATA_SOURCE_NAME: 'exporter:123456@(127.0.0.1:3306)'
        networks:
            - tiktok