run_server:
	go run main.go server.go user.go message.go

run_listen:
	go run ./client/listen.go ./client/message.go

run_send:
	go run ./client/send.go ./client/message.go

run_listen_send:
	go run ./client/send_listen.go ./client/message.go