// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tiktokuserservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "github.com/ozline/tiktok/services/user/kitex_gen/tiktok/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PingPong(ctx context.Context, Req *user.Request1, callOptions ...callopt.Option) (r *user.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTiktokUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTiktokUserServiceClient struct {
	*kClient
}

func (p *kTiktokUserServiceClient) PingPong(ctx context.Context, Req *user.Request1, callOptions ...callopt.Option) (r *user.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PingPong(ctx, Req)
}
