// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tiktokauthservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	auth "github.com/ozline/tiktok/services/auth/kitex_gen/tiktok/auth"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, Req *auth.PingRequest, callOptions ...callopt.Option) (r *auth.PingResponse, err error)
	GetToken(ctx context.Context, Req *auth.GetTokenRequest, callOptions ...callopt.Option) (r *auth.GetTokenResponse, err error)
	CheckToken(ctx context.Context, Req *auth.CheckTokenRequest, callOptions ...callopt.Option) (r *auth.CheckTokenResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTiktokAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTiktokAuthServiceClient struct {
	*kClient
}

func (p *kTiktokAuthServiceClient) Ping(ctx context.Context, Req *auth.PingRequest, callOptions ...callopt.Option) (r *auth.PingResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, Req)
}

func (p *kTiktokAuthServiceClient) GetToken(ctx context.Context, Req *auth.GetTokenRequest, callOptions ...callopt.Option) (r *auth.GetTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetToken(ctx, Req)
}

func (p *kTiktokAuthServiceClient) CheckToken(ctx context.Context, Req *auth.CheckTokenRequest, callOptions ...callopt.Option) (r *auth.CheckTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckToken(ctx, Req)
}
