global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'redis_exporter'
    static_configs:
    - targets: ['redis-exporter:9121']
  - job_name: 'mysql_exporter'
    static_configs:
    - targets: ['mysql-exporter:9104']