// Code generated by Kitex v0.4.4. DO NOT EDIT.

package kitexprotobuf

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	kitex_gen "github.com/ozline/tiktok/services/user/kitex_gen/kitex_gen"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return kitexProtoBufServiceInfo
}

var kitexProtoBufServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "kitexProtoBuf"
	handlerType := (*kitex_gen.KitexProtoBuf)(nil)
	methods := map[string]kitex.MethodInfo{
		"MyHandT1": kitex.NewMethodInfo(myHandT1Handler, newMyHandT1Args, newMyHandT1Result, false),
	}
	extra := map[string]interface{}{
		"PackageName": "",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func myHandT1Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.Request1)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.KitexProtoBuf).MyHandT1(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *MyHandT1Args:
		success, err := handler.(kitex_gen.KitexProtoBuf).MyHandT1(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MyHandT1Result)
		realResult.Success = success
	}
	return nil
}
func newMyHandT1Args() interface{} {
	return &MyHandT1Args{}
}

func newMyHandT1Result() interface{} {
	return &MyHandT1Result{}
}

type MyHandT1Args struct {
	Req *kitex_gen.Request1
}

func (p *MyHandT1Args) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.Request1)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MyHandT1Args) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MyHandT1Args) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MyHandT1Args) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in MyHandT1Args")
	}
	return proto.Marshal(p.Req)
}

func (p *MyHandT1Args) Unmarshal(in []byte) error {
	msg := new(kitex_gen.Request1)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MyHandT1Args_Req_DEFAULT *kitex_gen.Request1

func (p *MyHandT1Args) GetReq() *kitex_gen.Request1 {
	if !p.IsSetReq() {
		return MyHandT1Args_Req_DEFAULT
	}
	return p.Req
}

func (p *MyHandT1Args) IsSetReq() bool {
	return p.Req != nil
}

type MyHandT1Result struct {
	Success *kitex_gen.Response
}

var MyHandT1Result_Success_DEFAULT *kitex_gen.Response

func (p *MyHandT1Result) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.Response)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MyHandT1Result) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MyHandT1Result) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MyHandT1Result) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in MyHandT1Result")
	}
	return proto.Marshal(p.Success)
}

func (p *MyHandT1Result) Unmarshal(in []byte) error {
	msg := new(kitex_gen.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MyHandT1Result) GetSuccess() *kitex_gen.Response {
	if !p.IsSetSuccess() {
		return MyHandT1Result_Success_DEFAULT
	}
	return p.Success
}

func (p *MyHandT1Result) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.Response)
}

func (p *MyHandT1Result) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MyHandT1(ctx context.Context, Req *kitex_gen.Request1) (r *kitex_gen.Response, err error) {
	var _args MyHandT1Args
	_args.Req = Req
	var _result MyHandT1Result
	if err = p.c.Call(ctx, "MyHandT1", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
