// Code generated by Kitex v0.4.4. DO NOT EDIT.
package kitexprotobuf

import (
	server "github.com/cloudwego/kitex/server"
	kitex_gen "github.com/ozline/tiktok/services/user/kitex_gen/kitex_gen"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_gen.KitexProtoBuf, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
