// Code generated by Kitex v0.4.4. DO NOT EDIT.
package tiktokuserservice

import (
	server "github.com/cloudwego/kitex/server"
	user "github.com/ozline/tiktok/kitex_gen/tiktok/user"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler user.TiktokUserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
