// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tiktokchatservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	chat "github.com/ozline/tiktok/kitex_gen/tiktok/chat"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendChatMessage(ctx context.Context, Req *chat.SendMessageRequest, callOptions ...callopt.Option) (r *chat.SendMessageResponse, err error)
	AcceptChatMessage(ctx context.Context, Req *chat.ReceiveMessageRequest, callOptions ...callopt.Option) (r *chat.ReceiveMessageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTiktokChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTiktokChatServiceClient struct {
	*kClient
}

func (p *kTiktokChatServiceClient) SendChatMessage(ctx context.Context, Req *chat.SendMessageRequest, callOptions ...callopt.Option) (r *chat.SendMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendChatMessage(ctx, Req)
}

func (p *kTiktokChatServiceClient) AcceptChatMessage(ctx context.Context, Req *chat.ReceiveMessageRequest, callOptions ...callopt.Option) (r *chat.ReceiveMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AcceptChatMessage(ctx, Req)
}
