// Code generated by Kitex v0.6.2. DO NOT EDIT.

package followservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	follow "github.com/ozline/tiktok/kitex_gen/follow"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Action(ctx context.Context, req *follow.ActionRequest, callOptions ...callopt.Option) (r *follow.ActionResponse, err error)
	FollowList(ctx context.Context, req *follow.FollowListRequest, callOptions ...callopt.Option) (r *follow.FollowListResponse, err error)
	FollowerList(ctx context.Context, req *follow.FollowerListRequest, callOptions ...callopt.Option) (r *follow.FollowerListResponse, err error)
	FriendList(ctx context.Context, req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error)
	FollowCount(ctx context.Context, req *follow.FollowCountRequest, callOptions ...callopt.Option) (r *follow.FollowCountResponse, err error)
	FollowerCount(ctx context.Context, req *follow.FollowerCountRequest, callOptions ...callopt.Option) (r *follow.FollowerCountResponse, err error)
	IsFollow(ctx context.Context, req *follow.IsFollowRequest, callOptions ...callopt.Option) (r *follow.IsFollowResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFollowServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFollowServiceClient struct {
	*kClient
}

func (p *kFollowServiceClient) Action(ctx context.Context, req *follow.ActionRequest, callOptions ...callopt.Option) (r *follow.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, req)
}

func (p *kFollowServiceClient) FollowList(ctx context.Context, req *follow.FollowListRequest, callOptions ...callopt.Option) (r *follow.FollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, req)
}

func (p *kFollowServiceClient) FollowerList(ctx context.Context, req *follow.FollowerListRequest, callOptions ...callopt.Option) (r *follow.FollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kFollowServiceClient) FriendList(ctx context.Context, req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}

func (p *kFollowServiceClient) FollowCount(ctx context.Context, req *follow.FollowCountRequest, callOptions ...callopt.Option) (r *follow.FollowCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowCount(ctx, req)
}

func (p *kFollowServiceClient) FollowerCount(ctx context.Context, req *follow.FollowerCountRequest, callOptions ...callopt.Option) (r *follow.FollowerCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerCount(ctx, req)
}

func (p *kFollowServiceClient) IsFollow(ctx context.Context, req *follow.IsFollowRequest, callOptions ...callopt.Option) (r *follow.IsFollowResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IsFollow(ctx, req)
}
