// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tiktokfollowservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	follow "github.com/ozline/tiktok/kitex_gen/tiktok/follow"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Ping(ctx context.Context, Req *follow.PingReq, callOptions ...callopt.Option) (r *follow.BaseRsp, err error)
	RelationAction(ctx context.Context, Req *follow.RelationActionReq, callOptions ...callopt.Option) (r *follow.BaseRsp, err error)
	RelationQuery(ctx context.Context, Req *follow.RelationQueryReq, callOptions ...callopt.Option) (r *follow.RelationQueryRsp, err error)
	FollowList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error)
	FollowerList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error)
	FriendList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTiktokFollowServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTiktokFollowServiceClient struct {
	*kClient
}

func (p *kTiktokFollowServiceClient) Ping(ctx context.Context, Req *follow.PingReq, callOptions ...callopt.Option) (r *follow.BaseRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ping(ctx, Req)
}

func (p *kTiktokFollowServiceClient) RelationAction(ctx context.Context, Req *follow.RelationActionReq, callOptions ...callopt.Option) (r *follow.BaseRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationAction(ctx, Req)
}

func (p *kTiktokFollowServiceClient) RelationQuery(ctx context.Context, Req *follow.RelationQueryReq, callOptions ...callopt.Option) (r *follow.RelationQueryRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationQuery(ctx, Req)
}

func (p *kTiktokFollowServiceClient) FollowList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowList(ctx, Req)
}

func (p *kTiktokFollowServiceClient) FollowerList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, Req)
}

func (p *kTiktokFollowServiceClient) FriendList(ctx context.Context, Req *follow.UserListReq, callOptions ...callopt.Option) (r *follow.UserListRsp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, Req)
}
