// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	api "github.com/ozline/tiktok/cmd/api/biz/model/api"
	"github.com/ozline/tiktok/cmd/api/biz/pack"
	"github.com/ozline/tiktok/cmd/api/biz/rpc"
	"github.com/ozline/tiktok/kitex_gen/interaction"
)

// FavoriteAction .
// @router /douyin/favorite/action [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.FavoriteActionResponse)

	err = rpc.FavoriteAction(ctx, &interaction.FavoriteActionRequest{
		Token:      req.Token,
		VideoId:    req.VideoID,
		ActionType: req.ActionType,
	})

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// FavoriteList .
// @router /douyin/favorite/list [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FavoriteListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.FavoriteListResponse)

	videoList, err := rpc.FavoriteList(ctx, &interaction.FavoriteListRequest{
		UserId: req.UserID,
		Token:  req.Token,
	})

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.VideoList = pack.VideoListFavorited(videoList)
	pack.SendResponse(c, resp)
}

// CommentAction .
// @router /douyin/comment/action [POST]
func CommentAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.CommentActionResponse)

	comment, err := rpc.CommentAction(ctx, &interaction.CommentActionRequest{
		VideoId:     req.VideoID,
		ActionType:  req.ActionType,
		CommentText: req.CommentText,
		CommentId:   req.CommentID,
		Token:       req.Token,
	})

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Comment = pack.Comment(comment)
	pack.SendResponse(c, resp)
}

// CommentList .
// @router /douyin/comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp := new(api.CommentListResponse)

	commentList, err := rpc.CommentList(ctx, &interaction.CommentListRequest{
		VideoId: req.VideoID,
		Token:   req.Token,
	})

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.CommentList = pack.CommentList(commentList)
	pack.SendResponse(c, resp)
}
