name: server deploy

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ACCESSKEYID }}
          key: ${{ secrets.ACCESSKEYSECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd /deploy
            sh restart-service-all.sh