name: basic-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: go mod tidy

      - name: Build target
        run: make build-all

      - name: Archive production
        uses: actions/upload-artifact@v3
        with:
          name: build-output-all
          path: output

  run-test:
    needs: build-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user, video, chat, interaction, follow]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Download production
        uses: actions/download-artifact@v3
        with:
          name: build-output-all

      - name: Set up environment
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.ci.yml"

      - name: Run local server
        run: nohup sh ./output/${{ matrix.service }}/bootstrap.sh > nohup.out 2> nohup.err < /dev/null &

      - name: Test interfaces
        run: go test -v ./test/${{ matrix.service }}/...