name: build and push docker image to aliyun

on:
  push:
    branches:
      - main

jobs:
  push-aliyun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.ALIYUNDOCKERLOGINUSERNAME }}
          password: ${{ secrets.ALIYUNDOCKERLOGINPASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/ozline/tiktok:v1
          platforms: linux/arm64, linux/amd64
